name: animal_switcher
description: A simple Flutter app that switches between a cat and a dog when the text is clicked.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true